# Generated by Django 4.1.2 on 2022-10-17 15:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='название подразделения'
                    ),
                ),
                ('slug', models.SlugField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                (
                    'tree_id',
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                ('level', models.PositiveIntegerField(editable=False)),
                (
                    'parent',
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='children',
                        to='employee_list.department',
                        verbose_name='подразделение выше',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                (
                    'position',
                    models.CharField(max_length=100, verbose_name='должность'),
                ),
                (
                    'date_of_employment',
                    models.DateField(verbose_name='дата приема на работу'),
                ),
                (
                    'salary',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name='размер заработной платы',
                    ),
                ),
                (
                    'department',
                    mptt.fields.TreeForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='employees',
                        to='employee_list.department',
                        verbose_name='подразделение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
