version: "3"

services:
  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_list
  web:
    image: employee_list:latest
    ports:
      - 8000:8000
    depends_on:
      - db
